"""initial schema

Revision ID: 075aec5f0113
Revises: 339e6dbd0b06
Create Date: 2026-02-19 21:56:12.727428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '075aec5f0113'
down_revision: Union[str, Sequence[str], None] = '339e6dbd0b06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('blocks', 'area',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.drop_column('blocks', 'utilized_area_ha')
    op.drop_column('blocks', 'in_production_fraction')
    op.add_column('farms', sa.Column('scale', sa.String(), nullable=False))
    op.alter_column('greenhouses', 'area',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.drop_column('greenhouses', 'utilized_area_ha')
    op.drop_column('greenhouses', 'in_production_fraction')
    op.alter_column('ponds', 'size',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.drop_column('ponds', 'utilized_area_ha')
    op.drop_column('ponds', 'in_production_fraction')
    op.add_column('tenants', sa.Column('email', sa.String(), nullable=False))
    op.add_column('tenants', sa.Column('address', sa.String(), nullable=True))
    op.add_column('tenants', sa.Column('phone_number', sa.String(), nullable=True))
    op.add_column('tenants', sa.Column('selected_modules', postgresql.ARRAY(sa.String()), nullable=True))
    op.create_unique_constraint(None, 'tenants', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tenants', type_='unique')
    op.drop_column('tenants', 'selected_modules')
    op.drop_column('tenants', 'phone_number')
    op.drop_column('tenants', 'address')
    op.drop_column('tenants', 'email')
    op.add_column('ponds', sa.Column('in_production_fraction', sa.NUMERIC(), server_default=sa.text('1.0'), autoincrement=False, nullable=True))
    op.add_column('ponds', sa.Column('utilized_area_ha', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.alter_column('ponds', 'size',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.add_column('greenhouses', sa.Column('in_production_fraction', sa.NUMERIC(), server_default=sa.text('1.0'), autoincrement=False, nullable=True))
    op.add_column('greenhouses', sa.Column('utilized_area_ha', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.alter_column('greenhouses', 'area',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.drop_column('farms', 'scale')
    op.add_column('blocks', sa.Column('in_production_fraction', sa.NUMERIC(), server_default=sa.text('1.0'), autoincrement=False, nullable=True))
    op.add_column('blocks', sa.Column('utilized_area_ha', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.alter_column('blocks', 'area',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    # ### end Alembic commands ###
