"""add tenants

Revision ID: 339e6dbd0b06
Revises: 62f4ee7dc877
Create Date: 2026-02-18 09:12:47.711208

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.sql import text

# revision identifiers, used by Alembic.
revision: str = '339e6dbd0b06'
down_revision: Union[str, Sequence[str], None] = '62f4ee7dc877'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1️⃣ Create tenants table
    op.create_table(
        'tenants',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('owner_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['owner_id'], ['users.id']),
    )

    op.create_index('ix_tenants_id', 'tenants', ['id'])

    # 2️⃣ Add tenant_id column as NULLABLE first
    op.add_column('farms', sa.Column('tenant_id', sa.Integer(), nullable=True))

    # 3️⃣ Create ONE default tenant (only if farms exist)
    op.execute("""
        INSERT INTO tenants (name, owner_id)
        SELECT 'Default Tenant', owner_id
        FROM farms
        LIMIT 1
    """)

    # 4️⃣ Assign all farms to that tenant
    op.execute("""
        UPDATE farms
        SET tenant_id = (SELECT id FROM tenants LIMIT 1)
    """)

    # 5️⃣ Make column NOT NULL
    op.alter_column('farms', 'tenant_id', nullable=False)

    # 6️⃣ Add foreign key
    op.create_foreign_key(
        None,
        'farms',
        'tenants',
        ['tenant_id'],
        ['id']
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ponds', sa.Column('utilized_area_ha', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.add_column('ponds', sa.Column('in_production_fraction', sa.NUMERIC(), server_default=sa.text('1.0'), autoincrement=False, nullable=True))
    op.alter_column('ponds', 'size',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.add_column('greenhouses', sa.Column('utilized_area_ha', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.add_column('greenhouses', sa.Column('in_production_fraction', sa.NUMERIC(), server_default=sa.text('1.0'), autoincrement=False, nullable=True))
    op.alter_column('greenhouses', 'area',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.drop_constraint(None, 'farms', type_='foreignkey')
    op.drop_column('farms', 'tenant_id')
    op.add_column('blocks', sa.Column('utilized_area_ha', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.add_column('blocks', sa.Column('in_production_fraction', sa.NUMERIC(), server_default=sa.text('1.0'), autoincrement=False, nullable=True))
    op.alter_column('blocks', 'area',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.drop_index(op.f('ix_tenants_id'), table_name='tenants')
    op.drop_table('tenants')
    # ### end Alembic commands ###
