"""add active_modules to farms

Revision ID: 6519171fd9c6
Revises: 230869acb8b1
Create Date: 2026-02-14 06:28:50.587780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6519171fd9c6'
down_revision: Union[str, Sequence[str], None] = '230869acb8b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('farms', sa.Column('active_modules', sa.JSON(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('farms', 'active_modules')
    # ### end Alembic commands ###
