"""add hr_work_session_id to crop activities

Revision ID: f259a8ce7afe
Revises: 
Create Date: 2025-12-30 23:54:27.373358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f259a8ce7afe'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chemical_applications', sa.Column('hr_work_session_id', sa.Integer(), nullable=True))
    op.add_column('chemical_applications', sa.Column('labour_cost', sa.Float(), nullable=True))
    op.create_foreign_key(None, 'chemical_applications', 'hr_work_sessions', ['hr_work_session_id'], ['id'])
    op.add_column('crop_activities', sa.Column('hr_work_session_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'crop_activities', 'hr_work_sessions', ['hr_work_session_id'], ['id'])
    op.add_column('crop_harvests', sa.Column('hr_work_session_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'crop_harvests', 'hr_work_sessions', ['hr_work_session_id'], ['id'])
    op.add_column('fertilizer_applications', sa.Column('hr_work_session_id', sa.Integer(), nullable=True))
    op.add_column('fertilizer_applications', sa.Column('labour_cost', sa.Float(), nullable=True))
    op.create_foreign_key(None, 'fertilizer_applications', 'hr_work_sessions', ['hr_work_session_id'], ['id'])
    op.alter_column('hr_payments', 'module_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.add_column('hr_work_sessions', sa.Column('crop_id', sa.Integer(), nullable=True))
    op.add_column('hr_work_sessions', sa.Column('activity_id', sa.Integer(), nullable=True))
    op.alter_column('hr_work_sessions', 'module_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.create_foreign_key(None, 'hr_work_sessions', 'crops', ['crop_id'], ['id'])
    op.add_column('irrigations', sa.Column('hr_work_session_id', sa.Integer(), nullable=True))
    op.add_column('irrigations', sa.Column('labour_cost', sa.Float(), nullable=True))
    op.create_foreign_key(None, 'irrigations', 'hr_work_sessions', ['hr_work_session_id'], ['id'])
    op.add_column('land_preparations', sa.Column('hr_work_session_id', sa.Integer(), nullable=True))
    op.add_column('land_preparations', sa.Column('labour_cost', sa.Float(), nullable=True))
    op.create_foreign_key(None, 'land_preparations', 'hr_work_sessions', ['hr_work_session_id'], ['id'])
    op.add_column('nursery_activities', sa.Column('hr_work_session_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'nursery_activities', 'hr_work_sessions', ['hr_work_session_id'], ['id'])
    op.add_column('scouting_records', sa.Column('hr_work_session_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'scouting_records', 'hr_work_sessions', ['hr_work_session_id'], ['id'])
    op.add_column('weedings', sa.Column('hr_work_session_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'weedings', 'hr_work_sessions', ['hr_work_session_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'weedings', type_='foreignkey')
    op.drop_column('weedings', 'hr_work_session_id')
    op.drop_constraint(None, 'scouting_records', type_='foreignkey')
    op.drop_column('scouting_records', 'hr_work_session_id')
    op.drop_constraint(None, 'nursery_activities', type_='foreignkey')
    op.drop_column('nursery_activities', 'hr_work_session_id')
    op.drop_constraint(None, 'land_preparations', type_='foreignkey')
    op.drop_column('land_preparations', 'labour_cost')
    op.drop_column('land_preparations', 'hr_work_session_id')
    op.drop_constraint(None, 'irrigations', type_='foreignkey')
    op.drop_column('irrigations', 'labour_cost')
    op.drop_column('irrigations', 'hr_work_session_id')
    op.drop_constraint(None, 'hr_work_sessions', type_='foreignkey')
    op.alter_column('hr_work_sessions', 'module_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_column('hr_work_sessions', 'activity_id')
    op.drop_column('hr_work_sessions', 'crop_id')
    op.alter_column('hr_payments', 'module_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_constraint(None, 'fertilizer_applications', type_='foreignkey')
    op.drop_column('fertilizer_applications', 'labour_cost')
    op.drop_column('fertilizer_applications', 'hr_work_session_id')
    op.drop_constraint(None, 'crop_harvests', type_='foreignkey')
    op.drop_column('crop_harvests', 'hr_work_session_id')
    op.drop_constraint(None, 'crop_activities', type_='foreignkey')
    op.drop_column('crop_activities', 'hr_work_session_id')
    op.drop_constraint(None, 'chemical_applications', type_='foreignkey')
    op.drop_column('chemical_applications', 'labour_cost')
    op.drop_column('chemical_applications', 'hr_work_session_id')
    # ### end Alembic commands ###
